INFO:     Started server process [3417]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:38002 (Press CTRL+C to quit)
is_tty: False

[2024-05-20 15:16:13] [WARN ] [log_util.py] log_util.py:52 __init__() - ###################################################
[2024-05-20 15:16:13] [DEBUG] [log_util.py] log_util.py:54 __init__() - log_path: /Users/yutianran/Documents/MyCode/fish_util/src/log/log_util.py.log
2024/05/2024-05-20.md

[2024-05-20 15:16:14] [WARN ] [eagle_client.py] log_util.py:52 __init__() - ###################################################
[2024-05-20 15:16:14] [DEBUG] [eagle_client.py] log_util.py:54 __init__() - log_path: /Users/yutianran/Documents/MyCode/fish_script/client/log/eagle_client.py.log

[2024-05-20 15:16:14] [WARN ] [email_client.py] log_util.py:52 __init__() - ###################################################
[2024-05-20 15:16:14] [DEBUG] [email_client.py] log_util.py:54 __init__() - log_path: /Users/yutianran/Documents/MyCode/fish_script/client/log/email_client.py.log

[2024-05-20 15:16:14] [WARN ] [fastapi_client.py] log_util.py:52 __init__() - ###################################################
[2024-05-20 15:16:14] [DEBUG] [fastapi_client.py] log_util.py:54 __init__() - log_path: /Users/yutianran/Documents/MyCode/fish_script/client/log/fastapi_client.py.log
[2024-05-20 15:16:14] [DEBUG] [fastapi_client.py] fastapi_client.py:158 <module>() - Starting FastAPI server at http://localhost:38001/docs
INFO:     127.0.0.1:61088 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:61088 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61089 - "POST /tasks/?url=https%3A%2F%2Fmp.weixin.qq.com%2Fs%2FH6zP-96yXqoz_O5Rn1eIjA HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yutianran/Documents/MyCode/fish_script/client/fastapi_client.py", line 137, in create_task
    task = url2md.delay(url)
           ^^^^^^^^^^^^^^^^^
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/celery/app/task.py", line 444, in delay
    return self.apply_async(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yutianran/anaconda3/lib/python3.11/site-packages/celery/app/task.py", line 559, in apply_async
    check_arguments(*(args or ()), **(kwargs or {}))
TypeError: url2md() takes 1 positional argument but 2 were given
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [3417]
